name: Provision Longhorn
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Provision Longhorn
    runs-on: ubuntu-dagger
    steps:
      - name: Checkout infrastructure config
        uses: actions/checkout@v6

      - name: Deploy with helmfile
        run: |
          helmfile apply --suppress-secrets
